### ISSUE TITLE
Sidebar/File Tree not displaying

### ISSUE THREAD

**Issue by jmes** [dshemendiuk/Brackets-Espresso-Theme#1]
<img width="263" alt="screen shot 2016-03-11 at 16 52 21" src="https://cloud.githubusercontent.com/assets/2218236/13709017/a9db9828-e7a9-11e5-9b44-eb52caaeba69.png">

This seems to happen on OSX 10.9.5 with no other extensions installed. Flagging as I'm unsure how to fix.

**Comment by dshemendiuk** [comment]
Thanks for feedback @jmes. Check out the latest version. I've hopefully fixed the issue.
